#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  block compile virtualenv

  ln -ngs "$shome/vendor/virtualenv/bin/slcli" "$shome/bin/"
}

bootstrap
